### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by mohamed-abdul-fattah** [mohamed-abdul-fattah/life-system#3]
Create simple [wireframes](https://en.wikipedia.org/wiki/Website_wireframe) for the current pages new design. Current pages include the following
- Login
- Homepage
- List expenses
- Add new expense
- Edit expense

You can use [draw.io](http://draw.io/) to create simple wireframes like the following [example wireframe](https://drive.google.com/file/d/1tXfQuQ2jkdkEQN71Yn_3hlmYWx4PVUFE/view?usp=sharing)
_Wireframes are as simple as just designing the layouts for a page to get an overview of the design_

**Comment by El-amiir** [comment]
Not applicable as we're not redesigning. The current design is used as-is.
